---
- become: true
  hosts: localhost
  name: Configure SSH

  vars_files:
  - vars/variables.json

  tasks:
  - name: Ensure the hardened SSH config replaces the default config
    ansible.builtin.template:
      backup: true
      dest: /etc/ssh/sshd_config
      group: root
      mode: "u=rw"
      owner: root
      src: templates/sshd_config.j2
      validate: /usr/sbin/sshd -t -f %s
    notify: Restart ssh

  - name: Ensure the SSH banner is in place
    ansible.builtin.copy:
      dest: /etc/ssh/banner
      src: files/banner

  - name: Ensure the SSH daemon is enabled and running
    ansible.builtin.systemd:
      enabled: true
      name: sshd
      state: started

  handlers:
    - name: Restart ssh
      ansible.builtin.systemd:
        name: sshd
        daemon_reload: true
        enabled: true
        state: restarted
